[template]
src = "production.tmpl"
dest = "public/env-config.js"
keys = [
  "/configuration/access/token/attribute/name",
  "/configuration/access/token/injection/type",
  "/configuration/access/token/value",
  "/configuration/public/url",
  "/configuration/language",
  "/configuration/map/center",
  "/configuration/map/zoom",
  "/configuration/base/maps",
  "/configuration/default/terrain/provider/url",
  "/configuration/csw/3d/url",
  "/configuration/extractable/manager/url",
  "/configuration/show/poi/tool"
]
