apiVersion: v2
description: A Helm chart for Coordinate Extract App
name: coordinate-extract-app
version: 3.2.1
appVersion: 3.2.1
dependencies:
  - name: helm-common
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm
