apiVersion: v2
description: A Helm chart for MapColonies app boilerplate
name: app-boilerplate
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: helm-common
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm
