apiVersion: v2
description: A Helm chart for Coordinate Extract App
name: coordinate-extract-app
version: 1.1.8
appVersion: 1.1.8
dependencies:
  - name: helm-common
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm
